
import './globals.scss'

import {Inter, Nunito, Roboto} from 'next/font/google'
import {ModalProvider} from "@/components/providers/ModalContext";
import Footer from "@/components/Footer";
import Header from "@/components/Header";


const roboto = Roboto({
  variable: '--font-roboto',
  weight: ["300", "700", "500"],
  preload: false
})


const nunito = Nunito({
  preload: false,
  variable: '--font-nunito',
  weight: ["300", "700", "600", "800"],
  subsets: ['cyrillic', 'latin']
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body style={nunito.style}>
      <ModalProvider>
          <Header/>
            <main>
                {children}
            </main>
          <Footer/>
      </ModalProvider>
      </body>
    </html>
  )
}
